image: r-base

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - make ci-test

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
