image: r-base

stages:
  - test
  - deploy

before_script:
  - Rscript GetDevtools.R

test:
  stage: test
  script:
    - R -e "library(devtools); devtools::test()"

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
